In [74]:
import pandas as pd

In [75]:
df = pd.read_csv('ulus.csv')
df.head()

,Улус;Администр. центр;Площадь,тыс.км2;Численность населения (2002 г.),чел;Расст до Якт наземным;Расст до Якт водным;Расст до Якт воздушным;городов респ;городов улусного;поселков;сел;наслегов
0,Абыйский;п. Белая Гора;69,4;4750;1950/2900;3243;1148;-;-;1;6;5,NaN
1,Алданский;г. Алдан;156,8;49346;534;-;470;-;2;4;13;3,NaN
2,Аллаиховский;п. Чокурдах;107,3;3421;2700;2830;1290;-;-;1;6;5,NaN
3,Амгинский;с. Амга;29,4;17251;201;1036;200;-;-;-;21;14,NaN
4,Анабарский;с. Саскылах;55,6;4024;2621;2835;1285;-;-;-;3;3,NaN

In [76]:
df = pd.read_csv('ulus.csv', sep=';')
df.head()

,Улус,Администр. центр,"Площадь, тыс.км2","Численность населения (2002 г.), чел",Расст до Якт наземным,Расст до Якт водным,Расст до Якт воздушным,городов респ,городов улусного,поселков,сел,наслегов
0,Абыйский,п. Белая Гора,"69,4",4750.0,1950/2900,3243,1148,-,-,1,6.0,5.0
1,Алданский,г. Алдан,"156,8",49346.0,534,-,470,-,2,4,13.0,3.0
2,Аллаиховский,п. Чокурдах,"107,3",3421.0,2700,2830,1290,-,-,1,6.0,5.0
3,Амгинский,с. Амга,"29,4",17251.0,201,1036,200,-,-,-,21.0,14.0
4,Анабарский,с. Саскылах,"55,6",4024.0,2621,2835,1285,-,-,-,3.0,3.0

In [86]:
df.dtypes

Улус                                      object
Администр. центр                          object
Площадь, тыс.км2                          object
Численность населения (2002  г.), чел    float64
Расст до Якт наземным                     object
Расст до Якт водным                       object
Расст до Якт воздушным                    object
городов респ                              object
городов улусного                          object
поселков                                  object
сел                                      float64
наслегов                                 float64
area                                      object
density                                   object
dtype: object

In [78]:
df.columns

Index(['Улус', 'Администр. центр', 'Площадь, тыс.км2',
       'Численность населения (2002  г.), чел', 'Расст до Якт наземным',
       'Расст до Якт водным', 'Расст до Якт воздушным', 'городов респ',
       'городов улусного', 'поселков', 'сел', 'наслегов'],
      dtype='object')

In [79]:
df['сел']

0      6.0
1     13.0
2      6.0
3     21.0
4      3.0
5      9.0
6     29.0
7      5.0
8     26.0
9     25.0
10    16.0
11     5.0
12    22.0
13    16.0
14    35.0
15     8.0
16     7.0
17    24.0
18     2.0
19    12.0
20    23.0
21    13.0
22    52.0
23     4.0
24     NaN
25    14.0
26    39.0
27    15.0
28    12.0
29    35.0
30    10.0
31     7.0
32    27.0
33    30.0
34     4.0
35    11.0
Name: сел, dtype: float64

In [94]:
df.head()

,Улус,Администр. центр,"Площадь, тыс.км2","Численность населения (2002 г.), чел",Расст до Якт наземным,Расст до Якт водным,Расст до Якт воздушным,городов респ,городов улусного,поселков,сел,наслегов,area,density
0,Абыйский,п. Белая Гора,"69,4",4750.0,1950/2900,3243,1148,-,-,1,6.0,5.0,"69,4","69,4"
1,Алданский,г. Алдан,"156,8",49346.0,534,-,470,-,2,4,13.0,3.0,"156,8","156,8"
2,Аллаиховский,п. Чокурдах,"107,3",3421.0,2700,2830,1290,-,-,1,6.0,5.0,"107,3","107,3"
3,Амгинский,с. Амга,"29,4",17251.0,201,1036,200,-,-,-,21.0,14.0,"29,4","29,4"
4,Анабарский,с. Саскылах,"55,6",4024.0,2621,2835,1285,-,-,-,3.0,3.0,"55,6","55,6"

In [81]:
df['area'] = df['Площадь, тыс.км2']

In [106]:
df.head()

,Улус,Администр. центр,"Площадь, тыс.км2","Численность населения (2002 г.), чел",Расст до Якт наземным,Расст до Якт водным,Расст до Якт воздушным,городов респ,городов улусного,поселков,сел,наслегов,area,density
0,Абыйский,п. Белая Гора,"69,4",4750.0,1950/2900,3243,1148,-,-,1,6.0,5.0,"69,4","69,4"
1,Алданский,г. Алдан,"156,8",49346.0,534,-,470,-,2,4,13.0,3.0,"156,8","156,8"
2,Аллаиховский,п. Чокурдах,"107,3",3421.0,2700,2830,1290,-,-,1,6.0,5.0,"107,3","107,3"
3,Амгинский,с. Амга,"29,4",17251.0,201,1036,200,-,-,-,21.0,14.0,"29,4","29,4"
4,Анабарский,с. Саскылах,"55,6",4024.0,2621,2835,1285,-,-,-,3.0,3.0,"55,6","55,6"

In [92]:
df['area'] = df['Площадь, тыс.км2']

In [101]:
df['area'].replace()

0      69,4
1     156,8
2     107,3
3      29,4
4      55,6
5     223,6
6        42
7      67,8
8     137,4
9      55,2
10     45,6
11    140,2
12    107,8
13       77
14     11,7
15    165,8
16    104,6
17     11,9
18     98,9
19     87,1
20     52,4
21     92,3
22    160,8
23      318
24      318
25    125,2
26     57,8
27       19
28    135,8
29     18,3
30     95,3
31    120,3
32     24,7
33     12,6
34     52,3
35      3,6
Name: area, dtype: object

In [108]:
def replace_comma(s):
    return s.replace(',','.') if type(s)==str else '0'

In [109]:
df['area']=df['Площадь, тыс.км2'].apply(replace_comma)

In [110]:
df['area']=df['area'].astype(float)

In [111]:
df.head()

,Улус,Администр. центр,"Площадь, тыс.км2","Численность населения (2002 г.), чел",Расст до Якт наземным,Расст до Якт водным,Расст до Якт воздушным,городов респ,городов улусного,поселков,сел,наслегов,area,density
0,Абыйский,п. Белая Гора,"69,4",4750.0,1950/2900,3243,1148,-,-,1,6.0,5.0,69.4,"69,4"
1,Алданский,г. Алдан,"156,8",49346.0,534,-,470,-,2,4,13.0,3.0,156.8,"156,8"
2,Аллаиховский,п. Чокурдах,"107,3",3421.0,2700,2830,1290,-,-,1,6.0,5.0,107.3,"107,3"
3,Амгинский,с. Амга,"29,4",17251.0,201,1036,200,-,-,-,21.0,14.0,29.4,"29,4"
4,Анабарский,с. Саскылах,"55,6",4024.0,2621,2835,1285,-,-,-,3.0,3.0,55.6,"55,6"

In [116]:
df.dtypes

Улус                                      object
Администр. центр                          object
Площадь, тыс.км2                          object
Численность населения (2002  г.), чел    float64
Расст до Якт наземным                     object
Расст до Якт водным                       object
Расст до Якт воздушным                    object
городов респ                              object
городов улусного                          object
поселков                                  object
сел                                      float64
наслегов                                 float64
area                                     float64
density                                  float64
dtype: object

In [113]:
df['density']=df['Площадь, тыс.км2'].apply(replace_comma)

In [114]:
df['density']=df['density'].astype(float)

In [115]:
df.head()

,Улус,Администр. центр,"Площадь, тыс.км2","Численность населения (2002 г.), чел",Расст до Якт наземным,Расст до Якт водным,Расст до Якт воздушным,городов респ,городов улусного,поселков,сел,наслегов,area,density
0,Абыйский,п. Белая Гора,"69,4",4750.0,1950/2900,3243,1148,-,-,1,6.0,5.0,69.4,69.4
1,Алданский,г. Алдан,"156,8",49346.0,534,-,470,-,2,4,13.0,3.0,156.8,156.8
2,Аллаиховский,п. Чокурдах,"107,3",3421.0,2700,2830,1290,-,-,1,6.0,5.0,107.3,107.3
3,Амгинский,с. Амга,"29,4",17251.0,201,1036,200,-,-,-,21.0,14.0,29.4,29.4
4,Анабарский,с. Саскылах,"55,6",4024.0,2621,2835,1285,-,-,-,3.0,3.0,55.6,55.6

In [117]:
df.dtypes

Улус                                      object
Администр. центр                          object
Площадь, тыс.км2                          object
Численность населения (2002  г.), чел    float64
Расст до Якт наземным                     object
Расст до Якт водным                       object
Расст до Якт воздушным                    object
городов респ                              object
городов улусного                          object
поселков                                  object
сел                                      float64
наслегов                                 float64
area                                     float64
density                                  float64
dtype: object

In [118]:
df.drop([24], inplace=True)

In [119]:
df['density'] = df['Численность населения\xa0(2002\xa0 г.), чел']/(1000*df['area'])

In [120]:
df.drop(columns=['desnity'])

KeyError: "['desnity'] not found in axis"

In [121]:
df['Улус'][df['density'].idxmin()]

'Оленекский эвенкийский национальный'

In [129]:
df.head()

,Улус,Администр. центр,"Площадь, тыс.км2","Численность населения (2002 г.), чел",Расст до Якт наземным,Расст до Якт водным,Расст до Якт воздушным,городов респ,городов улусного,поселков,сел,наслегов,area,density,relation
0,Абыйский,п. Белая Гора,"69,4",4750.0,1950,3243,1148,-,-,1,6.0,5.0,69.4,0.068444,1950
1,Алданский,г. Алдан,"156,8",49346.0,534,-,470,-,2,4,13.0,3.0,156.8,0.314707,534
2,Аллаиховский,п. Чокурдах,"107,3",3421.0,2700,2830,1290,-,-,1,6.0,5.0,107.3,0.031883,2700
3,Амгинский,с. Амга,"29,4",17251.0,201,1036,200,-,-,-,21.0,14.0,29.4,0.586769,201
4,Анабарский,с. Саскылах,"55,6",4024.0,2621,2835,1285,-,-,-,3.0,3.0,55.6,0.072374,2621

In [134]:
df['Расст до Якт наземным']=df['Расст до Якт наземным'].astype(int)

ValueError: invalid literal for int() with base 10: '334/527'

In [132]:
df['relation'] = df['Расст до Якт наземным']/df['Расст до Якт воздушным']

TypeError: unsupported operand type(s) for /: 'int' and 'str'